    AWSTemplateFormatVersion: 2010-09-09
    Description: Answer Digital DevOps Academy

    Parameters:
      VpcCIDRSubnet1:
        Description: Please enter the IP range (CIDR notation) for this VPC
        Type: String
        MinLength: "9"
        MaxLength: "18"
        AllowedPattern: "^[0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2}\/[0-9]{1,2}"
        Default: 10.10.10.0/24
      VpcCIDRSubnet2:
        Description: Please enter the IP range (CIDR notation) for this VPC
        Type: String
        MinLength: "9"
        MaxLength: "18"
        AllowedPattern: "^[0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2}\/[0-9]{1,2}"
        Default: 10.10.11.0/24
      DeployedBy:
        Description: Please enter the name of who is deploying this resource.
        Type: String
        Default: Jackson M

    Resources:
      VPC:
        Type: AWS::EC2::VPC
        Properties:
          CidrBlock: "10.10.10.0/20"
          EnableDnsHostnames: false
          EnableDnsSupport: true
          Tags:
            - Key: "Name"
              Value: "VPC" 
            - Key: "managed-by"
              Value: "CloudFormation"
            - Key: "deployed-by"
              Value: !Ref DeployedBy  

      Subnet1:
        Type: AWS::EC2::Subnet
        Properties:
          VpcId: !Ref VPC
          AvailabilityZone: !Select [ 0, !GetAZs  '' ]
          CidrBlock: !Ref VpcCIDRSubnet1
          MapPublicIpOnLaunch: true
          Tags:
            - Key: "managed-by"
              Value: "CloudFormation"
            - Key: "deployed-by"
              Value: !Ref DeployedBy

      Subnet2:
        Type: AWS::EC2::Subnet
        Properties:
          VpcId: !Ref VPC
          AvailabilityZone: !Select [ 0, !GetAZs  '' ]
          CidrBlock: !Ref VpcCIDRSubnet2
          MapPublicIpOnLaunch: true
          Tags:
            - Key: "managed-by"
              Value: "CloudFormation"
            - Key: "deployed-by"
              Value: !Ref DeployedBy

    Outputs:
      VPC:
        Description: A reference to the created VPC
        Value: !Ref VPC